// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPermissionFieldNames          = builder.RawFieldNames(&SysPermission{})
	sysPermissionRows                = strings.Join(sysPermissionFieldNames, ",")
	sysPermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPermissionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysPermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(sysPermissionFieldNames, "`permission_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysPermissionModel interface {
		Insert(ctx context.Context, data *SysPermission) (sql.Result, error)
		FindOne(ctx context.Context, permissionId string) (*SysPermission, error)
		FindOneByPermissionCode(ctx context.Context, permissionCode string) (*SysPermission, error)
		Update(ctx context.Context, data *SysPermission) error
		Delete(ctx context.Context, permissionId string) error
	}

	defaultSysPermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysPermission struct {
		PermissionId       string         `db:"permission_id"`        // 权限唯一标识
		PermissionName     string         `db:"permission_name"`      // 权限名称，如“产品管理-新增”“开户操作”“清算处理”
		PermissionCode     string         `db:"permission_code"`      // 权限编码，如“product:add”“customer:openAccount”“liquidation:process”
		PermissionType     string         `db:"permission_type"`      // 权限类型，如“菜单权限”“按钮权限”
		ParentPermissionId sql.NullString `db:"parent_permission_id"` // 父权限ID，用于构建权限层级
		CreateTime         time.Time      `db:"create_time"`          // 权限创建时间
		UpdateTime         time.Time      `db:"update_time"`          // 权限信息更新时间
		DeletedAt          sql.NullTime   `db:"deleted_at"`
	}
)

func newSysPermissionModel(conn sqlx.SqlConn) *defaultSysPermissionModel {
	return &defaultSysPermissionModel{
		conn:  conn,
		table: "`sys_permission`",
	}
}

func (m *defaultSysPermissionModel) Delete(ctx context.Context, permissionId string) error {
	query := fmt.Sprintf("delete from %s where `permission_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, permissionId)
	return err
}

func (m *defaultSysPermissionModel) FindOne(ctx context.Context, permissionId string) (*SysPermission, error) {
	query := fmt.Sprintf("select %s from %s where `permission_id` = ? limit 1", sysPermissionRows, m.table)
	var resp SysPermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPermissionModel) FindOneByPermissionCode(ctx context.Context, permissionCode string) (*SysPermission, error) {
	var resp SysPermission
	query := fmt.Sprintf("select %s from %s where `permission_code` = ? limit 1", sysPermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, permissionCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPermissionModel) Insert(ctx context.Context, data *SysPermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, sysPermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PermissionId, data.PermissionName, data.PermissionCode, data.PermissionType, data.ParentPermissionId, data.DeletedAt)
	return ret, err
}

func (m *defaultSysPermissionModel) Update(ctx context.Context, newData *SysPermission) error {
	query := fmt.Sprintf("update %s set %s where `permission_id` = ?", m.table, sysPermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PermissionName, newData.PermissionCode, newData.PermissionType, newData.ParentPermissionId, newData.DeletedAt, newData.PermissionId)
	return err
}

func (m *defaultSysPermissionModel) tableName() string {
	return m.table
}
