// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRolePermissionFieldNames          = builder.RawFieldNames(&SysRolePermission{})
	sysRolePermissionRows                = strings.Join(sysRolePermissionFieldNames, ",")
	sysRolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysRolePermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysRolePermissionModel interface {
		Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRolePermission, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId string, permissionId string) (*SysRolePermission, error)
		Update(ctx context.Context, data *SysRolePermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRolePermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRolePermission struct {
		Id           int64     `db:"id"`            // 关联记录唯一标识，自增
		RoleId       string    `db:"role_id"`       // 角色ID，关联角色表
		PermissionId string    `db:"permission_id"` // 权限ID，关联权限表
		CreateTime   time.Time `db:"create_time"`   // 关联记录创建时间
	}
)

func newSysRolePermissionModel(conn sqlx.SqlConn) *defaultSysRolePermissionModel {
	return &defaultSysRolePermissionModel{
		conn:  conn,
		table: "`sys_role_permission`",
	}
}

func (m *defaultSysRolePermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRolePermissionModel) FindOne(ctx context.Context, id int64) (*SysRolePermission, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysRolePermissionRows, m.table)
	var resp SysRolePermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId string, permissionId string) (*SysRolePermission, error) {
	var resp SysRolePermission
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and `permission_id` = ? limit 1", sysRolePermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysRolePermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	return ret, err
}

func (m *defaultSysRolePermissionModel) Update(ctx context.Context, newData *SysRolePermission) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysRolePermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoleId, newData.PermissionId, newData.Id)
	return err
}

func (m *defaultSysRolePermissionModel) tableName() string {
	return m.table
}
