// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserFieldNames          = builder.RawFieldNames(&SysUser{})
	sysUserRows                = strings.Join(sysUserFieldNames, ",")
	sysUserRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysUserRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysUserModel interface {
		Insert(ctx context.Context, data *SysUser) (sql.Result, error)
		FindOne(ctx context.Context, userId string) (*SysUser, error)
		FindOneByUserName(ctx context.Context, userName string) (*SysUser, error)
		Update(ctx context.Context, data *SysUser) error
		Delete(ctx context.Context, userId string) error
	}

	defaultSysUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysUser struct {
		UserId             string         `db:"user_id"`              // 系统用户唯一标识，操作员ID
		UserName           string         `db:"user_name"`            // 用户名（登录账号）
		RealName           string         `db:"real_name"`            // 真实姓名
		Password           string         `db:"password"`             // 密码，加密存储（如MD5+盐值）
		RoleId             string         `db:"role_id"`              // 角色ID，关联角色表
		Department         sql.NullString `db:"department"`           // 所属部门，如“理财销售部”“运营部”
		Position           sql.NullString `db:"position"`             // 职位，如“柜台操作员”“运营专员”
		ContactPhone       sql.NullString `db:"contact_phone"`        // 联系电话
		UserStatus         string         `db:"user_status"`          // 用户状态，如“启用”“禁用”
		LastLoginTime      sql.NullTime   `db:"last_login_time"`      // 最后登录时间
		PasswordExpireTime time.Time      `db:"password_expire_time"` // 密码过期时间（默认90天）
		CreateTime         time.Time      `db:"create_time"`          // 用户创建时间
		UpdateTime         time.Time      `db:"update_time"`          // 用户信息更新时间
		DeletedAt          sql.NullTime   `db:"deleted_at"`
	}
)

func newSysUserModel(conn sqlx.SqlConn) *defaultSysUserModel {
	return &defaultSysUserModel{
		conn:  conn,
		table: "`sys_user`",
	}
}

func (m *defaultSysUserModel) Delete(ctx context.Context, userId string) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultSysUserModel) FindOne(ctx context.Context, userId string) (*SysUser, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", sysUserRows, m.table)
	var resp SysUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) FindOneByUserName(ctx context.Context, userName string) (*SysUser, error) {
	var resp SysUser
	query := fmt.Sprintf("select %s from %s where `user_name` = ? limit 1", sysUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) Insert(ctx context.Context, data *SysUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserName, data.RealName, data.Password, data.RoleId, data.Department, data.Position, data.ContactPhone, data.UserStatus, data.LastLoginTime, data.PasswordExpireTime, data.DeletedAt)
	return ret, err
}

func (m *defaultSysUserModel) Update(ctx context.Context, newData *SysUser) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, sysUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserName, newData.RealName, newData.Password, newData.RoleId, newData.Department, newData.Position, newData.ContactPhone, newData.UserStatus, newData.LastLoginTime, newData.PasswordExpireTime, newData.DeletedAt, newData.UserId)
	return err
}

func (m *defaultSysUserModel) tableName() string {
	return m.table
}
