// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/Nozomi9967/wmss-user-rpc/internal/logic"
	"github.com/Nozomi9967/wmss-user-rpc/internal/svc"
	__ "github.com/Nozomi9967/wmss-user-rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 获取用户详情信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *__.GetUserRequest) (*__.GetUserResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
